{
 "title": "RuuviTags",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "sensor",
    "label": "Sensors",
    "query": "SHOW TAG VALUES WITH KEY = \"sensor\""
   },
   {
    "name": "address",
    "label": "Address",
    "query": "SHOW TAG VALUES WITH KEY = \"address\""
   },
   { "name": "query0" }
  ]
 },
 "panels": [
  {
   "title": "Notes",
   "type": "text",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "### Changes\n\n[20211103-13:31]: Updated Office network\n"
   }
  },
  {
   "title": "Accelerometer (RMS)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "alias": "$tag_sensor",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sensor" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "acc_rms",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperature [°C]",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "$tag_sensor",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sensor" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Battery Voltage [V]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "alias": "$tag_sensor",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sensor" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "battery",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "25" ], "type": "moving_average" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Pressure [Pa]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "alias": "$tag_sensor",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sensor" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pressure",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Humidity [%H]",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "alias": "$tag_sensor",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sensor" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "humidity",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Link Quality (ETX)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_sensor",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sensor" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "etx",
     "select": [
      [
       { "params": [ "etx" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "MEAN",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "etx",
     "select": [
      [
       { "params": [ "etx" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "25" ], "type": "moving_average" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Packet Delivery Rate (PDR) [%]",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_sensor",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sensor" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "seq_no",
     "select": [
      [
       { "params": [ "pdr" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "MEAN",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "seq_no",
     "select": [
      [
       { "params": [ "pdr" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "25" ], "type": "moving_average" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Network metrics",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "sensor" ], "type": "tag" },
      { "params": [ "address" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "etx",
     "select": [
      [
       { "params": [ "neigbour" ], "type": "field" }
      ],
      [
       { "params": [ "etx" ], "type": "field" }
      ],
      [
       { "params": [ "hops" ], "type": "field" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "sensor" ], "type": "tag" },
      { "params": [ "address" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "clock_drift",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ " *1000000" ], "type": "math" }
      ]
     ]
    }
   ]
  }
 ]
}