{
 "title": "Mira starter kit",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "nodes", "label": "nodes", "query": { "query": "" } },
   { "name": "metrics", "label": "metrics" }
  ]
 },
 "panels": [
  { "title": "Sensor Values", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Temperature [°C]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "alias": "$tag_sensor",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sensor" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "acc_rms",
     "query": "from(bucket: \"miradb\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"temperature\"\n  )",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Air Pressure [Pa]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "alias": "$tag_sensor",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sensor" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "acc_rms",
     "query": "from(bucket: \"miradb\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"pressure\"\n  )",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Accelerometer RMS [g]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "alias": "$tag_sensor",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sensor" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "acc_rms",
     "query": "from(bucket: \"miradb\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"acc_rms\"\n  )",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Relative Humidity [%]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "alias": "$tag_sensor",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sensor" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "acc_rms",
     "query": "from(bucket: \"miradb\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"humidity\"\n  )",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Topology and Network Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Network graph",
   "type": "nodeGraph",
   "gridPos": { "h": 21, "w": 10, "x": 0, "y": 20 },
   "targets": [
    {
     "columns": [
      { "selector": "address", "text": "id", "type": "string" },
      { "selector": "address", "text": "title", "type": "string" },
      { "selector": "last_mon_data.pdr_to_root", "text": "mainStat", "type": "number" },
      { "selector": "last_mon_data.routing_load", "text": "rx_load", "type": "number" },
      { "selector": "last_mon_data.rssi", "text": "rssi", "type": "number" },
      { "selector": "last_mac_stats.rx_missed_slots", "text": "detail__RX_missed", "type": "string" },
      { "selector": "last_mac_stats.tx_dropped", "text": "detail__TX_dropped", "type": "string" },
      { "selector": "last_mac_stats.tx_failed", "text": "detail__TX_failed", "type": "string" }
     ],
     "computed_columns": [
      { "selector": "rx_load/100", "text": "arc__rx_load", "type": "string" },
      { "selector": "1-(rx_load/100)", "text": "arc__rx_free", "type": "string" },
      { "selector": "rssi/10", "text": "secondaryStat", "type": "string" }
     ],
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "http://localhost:3001/v1/nodes",
     "url_options": { "data": "", "method": "GET" }
    },
    {
     "columns": [
      { "selector": "address", "text": "id", "type": "string" },
      { "selector": "address", "text": "source", "type": "string" },
      { "selector": "parent", "text": "target", "type": "string" },
      { "selector": "last_mon_data.pdr_to_parent", "text": "mainStat", "type": "number" },
      { "selector": "last_mon_data.rssi", "text": "rssi", "type": "number" }
     ],
     "computed_columns": [
      { "selector": "rssi/10", "text": "secondaryStat", "type": "string" }
     ],
     "filterExpression": "target != \"\"",
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "http://localhost:3001/v1/nodes",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Packet delivery rate to Gateway [%]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 10, "y": 20 },
   "targets": [
    {
     "columns": [
      { "selector": "time", "text": "time", "timestampFormat": "2006-01-02T15:04:05Z07:00", "type": "timestamp" },
      { "selector": "value", "text": " ", "type": "number" },
      { "selector": "address", "text": "", "type": "string" }
     ],
     "pagination_mode": "offset",
     "parser": "backend",
     "source": "url",
     "summarizeBy": "address",
     "type": "json",
     "url": "http://localhost:3001/v1/series/data/pdr_to_root",
     "url_options": {
      "data": "",
      "method": "GET",
      "params": [
       { "key": "start_time", "value": "${__from:date:iso}" },
       { "key": "end_time", "value": "${__to:date:iso}" },
       { "key": "per_page", "value": "10000" },
       { "key": "page", "value": "1" }
      ]
     }
    }
   ]
  },
  {
   "title": "Packet delivery rate to parent [%]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 20 },
   "targets": [
    {
     "columns": [
      { "selector": "time", "text": "time", "timestampFormat": "2006-01-02T15:04:05Z07:00", "type": "timestamp" },
      { "selector": "value", "text": " ", "type": "number" },
      { "selector": "address", "text": "", "type": "string" }
     ],
     "pagination_mode": "offset",
     "parser": "backend",
     "source": "url",
     "summarizeBy": "address",
     "type": "json",
     "url": "http://localhost:3001/v1/series/data/pdr_to_parent",
     "url_options": {
      "data": "",
      "method": "GET",
      "params": [
       { "key": "start_time", "value": "${__from:date:iso}" },
       { "key": "end_time", "value": "${__to:date:iso}" },
       { "key": "per_page", "value": "10000" },
       { "key": "page", "value": "1" }
      ]
     }
    }
   ]
  },
  {
   "title": "Battery Voltage [V]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 10, "y": 27 },
   "targets": [
    {
     "alias": "$tag_sensor",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sensor" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "acc_rms",
     "query": "from(bucket: \"miradb\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"battery\"\n  )",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "RF signal strength to parent [cBm RSSI]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 27 },
   "targets": [
    {
     "columns": [
      { "selector": "time", "text": "time", "timestampFormat": "2006-01-02T15:04:05Z07:00", "type": "timestamp" },
      { "selector": "value", "text": " ", "type": "number" },
      { "selector": "address", "text": "", "type": "string" }
     ],
     "pagination_mode": "offset",
     "parser": "backend",
     "source": "url",
     "summarizeBy": "address",
     "type": "json",
     "url": "http://localhost:3001/v1/series/data/rssi",
     "url_options": {
      "data": "",
      "method": "GET",
      "params": [
       { "key": "start_time", "value": "${__from:date:iso}" },
       { "key": "end_time", "value": "${__to:date:iso}" },
       { "key": "per_page", "value": "10000" },
       { "key": "page", "value": "1" }
      ]
     }
    }
   ]
  },
  {
   "title": "Used TX buffer [packets]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 10, "y": 34 },
   "targets": [
    {
     "columns": [
      { "selector": "time", "text": "time", "timestampFormat": "2006-01-02T15:04:05Z07:00", "type": "timestamp" },
      { "selector": "value", "text": " ", "type": "number" },
      { "selector": "address", "text": "", "type": "string" }
     ],
     "pagination_mode": "offset",
     "parser": "backend",
     "source": "url",
     "summarizeBy": "address",
     "type": "json",
     "url": "http://localhost:3001/v1/series/data/used_tx_queue",
     "url_options": {
      "data": "",
      "method": "GET",
      "params": [
       { "key": "start_time", "value": "${__from:date:iso}" },
       { "key": "end_time", "value": "${__to:date:iso}" },
       { "key": "per_page", "value": "10000" },
       { "key": "page", "value": "1" }
      ]
     }
    }
   ]
  },
  {
   "title": "Used RX bandwidth [%]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 34 },
   "targets": [
    {
     "columns": [
      { "selector": "time", "text": "time", "timestampFormat": "2006-01-02T15:04:05Z07:00", "type": "timestamp" },
      { "selector": "value", "text": " ", "type": "number" },
      { "selector": "address", "text": "", "type": "string" }
     ],
     "pagination_mode": "offset",
     "parser": "backend",
     "source": "url",
     "summarizeBy": "address",
     "type": "json",
     "url": "http://localhost:3001/v1/series/data/routing_load",
     "url_options": {
      "data": "",
      "method": "GET",
      "params": [
       { "key": "start_time", "value": "${__from:date:iso}" },
       { "key": "end_time", "value": "${__to:date:iso}" },
       { "key": "per_page", "value": "10000" },
       { "key": "page", "value": "1" }
      ]
     }
    }
   ]
  },
  {
   "title": "Data sent [bytes]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 41 },
   "targets": [
    {
     "columns": [
      { "selector": "time", "text": "time", "timestampFormat": "2006-01-02T15:04:05Z07:00", "type": "timestamp" },
      { "selector": "value", "text": " ", "type": "number" },
      { "selector": "address", "text": "", "type": "string" }
     ],
     "pagination_mode": "offset",
     "parser": "backend",
     "source": "url",
     "summarizeBy": "address",
     "type": "json",
     "url": "http://localhost:3001/v1/series/data/bytes_sent",
     "url_options": {
      "data": "",
      "method": "GET",
      "params": [
       { "key": "start_time", "value": "${__from:date:iso}" },
       { "key": "end_time", "value": "${__to:date:iso}" },
       { "key": "per_page", "value": "10000" },
       { "key": "page", "value": "1" }
      ]
     }
    }
   ]
  },
  {
   "title": "Packets Sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 41 },
   "targets": [
    {
     "columns": [
      { "selector": "time", "text": "time", "timestampFormat": "2006-01-02T15:04:05Z07:00", "type": "timestamp" },
      { "selector": "value", "text": " ", "type": "number" },
      { "selector": "address", "text": "", "type": "string" }
     ],
     "pagination_mode": "offset",
     "parser": "backend",
     "source": "url",
     "summarizeBy": "address",
     "type": "json",
     "url": "http://localhost:3001/v1/series/data/tx_unicast_packets",
     "url_options": {
      "data": "",
      "method": "GET",
      "params": [
       { "key": "start_time", "value": "${__from:date:iso}" },
       { "key": "end_time", "value": "${__to:date:iso}" },
       { "key": "per_page", "value": "10000" },
       { "key": "page", "value": "1" }
      ]
     }
    }
   ]
  },
  {
   "title": "Packets received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 41 },
   "targets": [
    {
     "columns": [
      { "selector": "time", "text": "time", "timestampFormat": "2006-01-02T15:04:05Z07:00", "type": "timestamp" },
      { "selector": "value", "text": " ", "type": "number" },
      { "selector": "address", "text": "", "type": "string" }
     ],
     "pagination_mode": "offset",
     "parser": "backend",
     "source": "url",
     "summarizeBy": "address",
     "type": "json",
     "url": "http://localhost:3001/v1/series/data/rx_unicast_packets",
     "url_options": {
      "data": "",
      "method": "GET",
      "params": [
       { "key": "start_time", "value": "${__from:date:iso}" },
       { "key": "end_time", "value": "${__to:date:iso}" },
       { "key": "per_page", "value": "10000" },
       { "key": "page", "value": "1" }
      ]
     }
    }
   ]
  }
 ]
}