{
 "title": "RuuviTags",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "sensor",
    "label": "Sensors",
    "query": "SHOW TAG VALUES WITH KEY = \"sensor\""
   },
   {
    "name": "address",
    "label": "Address",
    "query": "SHOW TAG VALUES WITH KEY = \"address\""
   }
  ]
 },
 "panels": [
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "$tag_sensor",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sensor" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=~", "value": "/^$sensor$/" }
     ]
    }
   ]
  },
  {
   "title": "Battery voltage",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "alias": "$tag_sensor",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sensor" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "battery",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "8" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=~", "value": "/^$sensor$/" }
     ]
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "pressurehpa" }
   ],
   "targets": [
    {
     "alias": "$tag_sensor",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sensor" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pressure",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=~", "value": "/^$sensor$/" }
     ]
    }
   ]
  },
  {
   "title": "Network metrics",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "sensor" ], "type": "tag" },
      { "params": [ "address" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "etx",
     "select": [
      [
       { "params": [ "neigbour" ], "type": "field" }
      ],
      [
       { "params": [ "etx" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=~", "value": "/^$sensor$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "sensor" ], "type": "tag" },
      { "params": [ "address" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "clock_drift",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=~", "value": "/^$sensor$/" }
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "humidity" }
   ],
   "targets": [
    {
     "alias": "$tag_sensor",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sensor" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "humidity",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=~", "value": "/^$sensor$/" }
     ]
    }
   ]
  },
  {
   "title": "ETX",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_sensor",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sensor" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "etx",
     "select": [
      [
       { "params": [ "etx" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=~", "value": "/^$sensor$/" }
     ]
    },
    {
     "alias": "MEAN",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "etx",
     "select": [
      [
       { "params": [ "etx" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "30" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=~", "value": "/^$sensor$/" }
     ]
    }
   ]
  },
  {
   "title": "Network topology",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 33, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "alias": "$tag_sensor",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sensor" ], "type": "tag" },
      { "params": [ "address" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "etx",
     "select": [
      [
       { "params": [ "neigbour" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sensor", "operator": "=~", "value": "/^$sensor$/" }
     ]
    }
   ]
  }
 ]
}