apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    url: http://influxdb:8086
    access: proxy
    database: miradb
    user: mirauser
    password: mirapassword
    isDefault: true
