apiVersion: 1

datasources:
  - name: influxdb-flux
    type: influxdb
    access: proxy
    url: http://localhost:8086
    user: admin
    password: admin_password
    isDefault: true
    secureJsonData:
      token: mytoken
    jsonData:
      version: Flux
      organization: myorg
      httpMode: GET
      defaultBucket: miramon
      tlsSkipVerify: true
  - name: Infinity
    type: yesoreyeram-infinity-datasource
    access: proxy
    jsonData:
      authenticationType: none
